---
- name: Create file on App Server 1
  hosts: app_server_1
  gather_facts: no
  tasks:
    - name: Create empty file /tmp/file.txt
      file:
        path: /tmp/file.txt
        state: touch
        mode: '0644'
